FA.JustBlog.HoangN34/FA.JustBlog/Controllers/CategoryController.cs
using FA.JustBlog.Service.CategoryService;
using FA.JustBlog.Service.PostService;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;
        private readonly IPostService _postService;

        public CategoryController(ICategoryService service, IPostService postService)
        {
            _service = service;
            _postService = postService;
        }

        public IActionResult CategoriesDropDown()
        {
            var listCategory = _service.GetCategoryDropDown();
            if (listCategory == null) return NotFound();

            return View(listCategory.Data);
        }

        [Route("Category/{category}")]
        public IActionResult GetPostByCategory(string category)
        {
            var listPostByCategory = _postService.GetDeailPostByCategory(category);
            if (listPostByCategory != null)
            {
                return View("~/Views/Post/Index.cshtml", listPostByCategory.Data);
            }
            return View();
        }
    }
}

FA.JustBlog.HoangN34/FA.JustBlog/Controllers/CommentController.cs
using FA.JustBlog.Model.CommentModel;
using FA.JustBlog.Service.CommentService;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _service;

        public CommentController(ICommentService service)
        {
            _service = service;
        }

        public IActionResult Index(int id)
        {
            var listComment = _service.GetCommentByPost(id).Data;
            if (listComment.Count > 0)
            {
                return PartialView("~/Views/Shared/_Comment.cshtml", listComment);
            }
            return Redirect("~Views/Shared/Error.cshtml");
        }

        [HttpPost]
        public IActionResult AddComment([FromBody] CommentDetailViewModel comment)
        {
            var listComment = _service.CreateComment(comment, comment.PostId);
            return StatusCode(listComment.Code);
        }
    }
}

FA.JustBlog.HoangN34/FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Service.PostService;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult Index()
        {
            var listPost = _postService.GetAllPost();
            if (listPost != null)
            {
                return View(listPost.Data);
            }
            ViewBag.Message = listPost.Message;
            return View();
        }

        public IActionResult LatestPost()
        {
            var listLasterPost = _postService.GetLastestPost(5);
            if (listLasterPost != null)
            {
                return PartialView("_ListPosts", listLasterPost.Data);
            }
            return PartialView();
        }
        public IActionResult DetailPost(int year, int month, string title)
        {
            var postViewModel = _postService.GetDetailPost(year, month, title);
            if (postViewModel != null)
            {
                return View(postViewModel.Data);
            }
            return View();
        }

        public IActionResult MostViewedPosts()
        {
            var listmost = _postService.GetMostPost(5);
            if (listmost != null)
            {
                return PartialView("_ListPosts", listmost.Data);
            }
            return PartialView();
        }

        [Route("Post/{urlSlug}")]
        public IActionResult GetPostByTag(string urlSlug)
        {
            if (string.IsNullOrEmpty(urlSlug))
            {
                ViewBag.Message = "Not Found";
            }
            var listPost = _postService.GetPostByTag(urlSlug);
            if (listPost != null)
            {
                return View("~/Views/Post/Index.cshtml", listPost.Data);
            }
            return View();
        }
    }
}

FA.JustBlog.HoangN34/FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Service.PostService;
using FA.JustBlog.Service.TagService;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers
{
    public class TagController : Controller
    {
        private readonly ITagService _service;
        private readonly PostService _postService;

        // GET: TagController
        public TagController(ITagService service, PostService postService)
        {
            _service = service;
            _postService = postService;
        }

        public ActionResult PopularTags()
        {
            var listTag = _service.GetPopularTag();
            if (listTag != null)
            {
                return PartialView(listTag.Data);
            }
            return PartialView();
        }

        public ActionResult GetPostByTag(string url)
        {
            var listPost = _postService.GetPostByTag(url);
            if (listPost != null)
            {
                return View("~/Views/Post/Index.cshtml", listPost);
            }
            return View();
        }
    }
}

FA.JustBlog.HoangN34/FA.JustBlog/Areas/Admin/Views/Shared/Error404.cshtml
@{
    ViewData["Title"] = "Error404";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="error-page pt-5">
    <h2 class="headline text-warning"> 404</h2>

    <div class="error-content">
        <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

        <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a asp-area="Admin" asp-controller="Home" asp-action="Index">return to dashboard</a> or try using the search form.
        </p>

        <form class="search-form">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" name="submit" class="btn btn-warning">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

FA.JustBlog.HoangN34/FA.JustBlog/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin | DardBoard</title>

    <!-- Google Font: Source Sans Pro -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">


    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-controller="Home" asp-action="Contact" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Login" asp-action="Logout" class="btn btn-primary">Logout</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="../../index3.html" class="brand-link">
                <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@ViewContext.HttpContext.User.Identity.Name</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>

                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="Post" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Post Manager</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="Category" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Category Manager</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="Tag" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Tag Manager</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="Comment" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Comment Manager</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="User" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>User Manager</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-controller="Role" asp-action="Index" asp-route-page="1" asp-route-pageSize="3" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Role Manager</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <partial name="_Notification" />
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>

    <script src="/lib/ckeditor/ckeditor.js"></script>
    <script src="/lib/ckeditor/adapters/jquery.js"></script>

    <script src="~/js/site.js"></script>



</body>
</html>

FA.JustBlog.HoangN34/FA.JustBlog/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="#" class="h1"><b>Admin</b>LTE</a>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                <div class="col-lg-12">
                    @RenderBody()
                </div>

               @* <p class="mb-1">
                    <a href="forgot-password.html">I forgot my password</a>
                </p>
                <p class="mb-0">
                    <a href="register.html" class="text-center">Register a new membership</a>
                </p>*@
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
</body>
</html>

FA.JustBlog.HoangN34/FA.JustBlog/Areas/Admin/Views/Shared/_Notification.cshtml
@if (TempData["Message"] != null && TempData["DataError"] == null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Message"]');
    </script>
}

@if (TempData["Message"] == null && TempData["DataError"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Message"]');
    </script>
}